#ifndef NEARGYE_MAGIC_ENUM_DETAIL_CONFIG_HPP
#define NEARGYE_MAGIC_ENUM_DETAIL_CONFIG_HPP

#ifdef MAGIC_ENUM_INTERFACE_UNIT
#define MAGIC_ENUM_BEGIN_MODULE_EXPORT export {
#define MAGIC_ENUM_END_MODULE_EXPORT }
#else
#define MAGIC_ENUM_BEGIN_MODULE_EXPORT
#define MAGIC_ENUM_END_MODULE_EXPORT
#endif

#if defined(MAGIC_ENUM_USE_MODULES) && !defined(MAGIC_ENUM_INTERFACE_UNIT)
import magic_enum;
#endif

#endif // NEARGYE_MAGIC_ENUM_DETAIL_CONFIG_HPP
