name: macos

on: [push, pull_request]

permissions: read-all

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
        - macos-15 # https://github.com/actions/runner-images/blob/main/images/macos/macos-15-Readme.md#xcode
        - macos-26 # https://github.com/actions/runner-images/blob/main/images/macos/macos-26-Readme.md#xcode
        compiler: [Apple Clang, GCC 16]
        build_type: [Release, Debug]

    name: "${{ matrix.os }} / ${{ matrix.compiler }} / ${{ matrix.build_type }}"
    runs-on: ${{ matrix.os }}
    env:
      CC: ${{ matrix.compiler == 'GCC 16' && 'gcc-16' || 'clang' }}
      CXX: ${{ matrix.compiler == 'GCC 16' && 'g++-16' || 'clang++' }}

    steps:
    - uses: actions/checkout@v7

    - name: Install GCC 16
      if: ${{ matrix.compiler == 'GCC 16' }}
      env:
        CC: clang
        CXX: clang++
      run: |
        brew install gcc@16
        echo "$(brew --prefix gcc@16)/bin" >> "${GITHUB_PATH}"

    - name: Configure
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - name: Build
      run: cmake --build build --parallel --config ${{ matrix.build_type }}

    - name: Test
      run: ctest --test-dir build --output-on-failure --no-tests=error -C ${{ matrix.build_type }}
