name: ubuntu_test_installed_version.yml

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v7

      - name: test installed package
        run: bash ./test_installed_version.bash
